config/routes.rb
Rails.application.routes.draw do

  get '/answer', to:'questions#answer'
  get '/ask' , to: 'questions#ask'
  # get 'questions/ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def answer

    @query = params[:query]
    if @query.include?("?")
      @answer = "Silly question, get dressed and go to work!"
    elsif @query == "I am going to work right now!"
      @answer = "Good job!!!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end

  end


  def ask
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Questions#answer</h1>
<p>Find me in app/views/questions/answer.html.erb</p>
<%= @query %>

<%= link_to "Ask a new question", ask_path %>

app/views/questions/ask.html.erb
<h1>Questions#ask</h1>
<p>Find me in app/views/questions/ask.html.erb</p>
    <form action="/answer" method='get'> <!--.# go to the mtehod answer in controller.-->
    <label for="question">Speak to your coach</label>
    <input type="text" id="question" name="query" placeholder="what time is it?"> <!--.# this it query so you will store it later in a variable.-->
    <input type="submit" value="Go on!">
    </form>